
language: cpp
os: osx
osx_image: xcode8.2


script:
  - cd ../
  - git clone https://github.com/openframeworks/openFrameworks.git
  - cd openframeworks
  - git checkout ee79e8bb6723380d3b6b794e81192d4035c1097b
  - cd ../
  - cp -r TravisCIWithOF openFrameworks/apps/
  - cd openframeworks/apps/TravisCIWithOF/
  - make
